// <auto-generated />
using System;
using GHPRS.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GHPRS.Persistence.Migrations
{
    [DbContext(typeof(GhprsContext))]
    [Migration("20220726081519_add_community_data")]
    partial class add_community_data
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GHPRS.Core.Entities.Column", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("WorkSheetId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkSheetId");

                    b.ToTable("Columns");
                });

            modelBuilder.Entity("GHPRS.Core.Entities.CommunityData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Agency")
                        .HasColumnType("text");

                    b.Property<string>("CLIENT_A_TX_CURR")
                        .HasColumnType("text");

                    b.Property<string>("CLIENT_A_TX_NEW")
                        .HasColumnType("text");

                    b.Property<string>("CONTACT_A")
                        .HasColumnType("text");

                    b.Property<string>("CONTACT_PEDS")
                        .HasColumnType("text");

                    b.Property<string>("CTC_CHILD")
                        .HasColumnType("text");

                    b.Property<string>("CTC_F_A")
                        .HasColumnType("text");

                    b.Property<string>("CTC_F_P")
                        .HasColumnType("text");

                    b.Property<string>("CTC_M_A")
                        .HasColumnType("text");

                    b.Property<string>("CTC_M_P")
                        .HasColumnType("text");

                    b.Property<string>("CTC_PWID")
                        .HasColumnType("text");

                    b.Property<string>("CTC_SEX")
                        .HasColumnType("text");

                    b.Property<string>("Council")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("District")
                        .HasColumnType("text");

                    b.Property<string>("HTS_F_A")
                        .HasColumnType("text");

                    b.Property<string>("HTS_F_P")
                        .HasColumnType("text");

                    b.Property<string>("HTS_M_A")
                        .HasColumnType("text");

                    b.Property<string>("HTS_M_P")
                        .HasColumnType("text");

                    b.Property<string>("HTS_PWID")
                        .HasColumnType("text");

                    b.Property<string>("IPV_HX_SCREEN")
                        .HasColumnType("text");

                    b.Property<string>("KNOWN_POS_A")
                        .HasColumnType("text");

                    b.Property<string>("KNOWN_POS_PEDS")
                        .HasColumnType("text");

                    b.Property<string>("LFTU")
                        .HasColumnType("text");

                    b.Property<string>("L_CTC")
                        .HasColumnType("text");

                    b.Property<string>("L_DXD")
                        .HasColumnType("text");

                    b.Property<string>("L_NOATTMPT")
                        .HasColumnType("text");

                    b.Property<string>("L_REFX")
                        .HasColumnType("text");

                    b.Property<string>("L_RTX")
                        .HasColumnType("text");

                    b.Property<string>("L_SELF_REF")
                        .HasColumnType("text");

                    b.Property<string>("L_UNBL")
                        .HasColumnType("text");

                    b.Property<string>("L_WRNGD")
                        .HasColumnType("text");

                    b.Property<string>("Month")
                        .HasColumnType("text");

                    b.Property<string>("NEG_A")
                        .HasColumnType("text");

                    b.Property<string>("NEG_PEDS")
                        .HasColumnType("text");

                    b.Property<string>("POS_A")
                        .HasColumnType("text");

                    b.Property<string>("POS_F_A")
                        .HasColumnType("text");

                    b.Property<string>("POS_F_P")
                        .HasColumnType("text");

                    b.Property<string>("POS_M_A")
                        .HasColumnType("text");

                    b.Property<string>("POS_M_P")
                        .HasColumnType("text");

                    b.Property<string>("POS_PEDS")
                        .HasColumnType("text");

                    b.Property<string>("POS_PWID")
                        .HasColumnType("text");

                    b.Property<string>("Partner")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.Property<string>("SCREEN_ELIG_F")
                        .HasColumnType("text");

                    b.Property<string>("SCREEN_ELIG_M")
                        .HasColumnType("text");

                    b.Property<string>("SCREEN_ELIG_PEDS")
                        .HasColumnType("text");

                    b.Property<string>("SCREEN_F")
                        .HasColumnType("text");

                    b.Property<string>("SCREEN_HTS_F")
                        .HasColumnType("text");

                    b.Property<string>("SCREEN_HTS_M")
                        .HasColumnType("text");

                    b.Property<string>("SCREEN_HTS_PEDS")
                        .HasColumnType("text");

                    b.Property<string>("SCREEN_HTS_POS_F")
                        .HasColumnType("text");

                    b.Property<string>("SCREEN_HTS_POS_M")
                        .HasColumnType("text");

                    b.Property<string>("SCREEN_HTS_POS_PEDS")
                        .HasColumnType("text");

                    b.Property<string>("SCREEN_M")
                        .HasColumnType("text");

                    b.Property<string>("SCREEN_PEDS")
                        .HasColumnType("text");

                    b.Property<string>("SiteId")
                        .HasColumnType("text");

                    b.Property<string>("TX_NEW_CHILD")
                        .HasColumnType("text");

                    b.Property<string>("TX_NEW_PWID")
                        .HasColumnType("text");

                    b.Property<string>("TX_NEW_SEX")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Ward")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("stg_community_data");
                });

            modelBuilder.Entity("GHPRS.Core.Entities.FacilityData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Agency")
                        .HasColumnType("text");

                    b.Property<string>("CLIENT_A_TX_CURR")
                        .HasColumnType("text");

                    b.Property<string>("CLIENT_A_TX_NEW")
                        .HasColumnType("text");

                    b.Property<string>("CONTACT_A")
                        .HasColumnType("text");

                    b.Property<string>("CONTACT_PEDS")
                        .HasColumnType("text");

                    b.Property<string>("Council")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("District")
                        .HasColumnType("text");

                    b.Property<string>("HTS_2_months")
                        .HasColumnType("text");

                    b.Property<string>("HTS_F_A")
                        .HasColumnType("text");

                    b.Property<string>("HTS_F_P")
                        .HasColumnType("text");

                    b.Property<string>("HTS_M_A")
                        .HasColumnType("text");

                    b.Property<string>("HTS_M_P")
                        .HasColumnType("text");

                    b.Property<string>("IPV_HX_SCREEN")
                        .HasColumnType("text");

                    b.Property<string>("KNOWN_POS_A")
                        .HasColumnType("text");

                    b.Property<string>("KNOWN_POS_PEDS")
                        .HasColumnType("text");

                    b.Property<string>("LCM_A")
                        .HasColumnType("text");

                    b.Property<string>("LFTU_A")
                        .HasColumnType("text");

                    b.Property<string>("LFTU_P")
                        .HasColumnType("text");

                    b.Property<string>("L_CTC_A")
                        .HasColumnType("text");

                    b.Property<string>("L_CTC_P")
                        .HasColumnType("text");

                    b.Property<string>("L_DXD_A")
                        .HasColumnType("text");

                    b.Property<string>("L_DXD_P")
                        .HasColumnType("text");

                    b.Property<string>("L_NOATTMPT_A")
                        .HasColumnType("text");

                    b.Property<string>("L_NOATTMPT_P")
                        .HasColumnType("text");

                    b.Property<string>("L_REFX_A")
                        .HasColumnType("text");

                    b.Property<string>("L_REFX_P")
                        .HasColumnType("text");

                    b.Property<string>("L_RTX_A")
                        .HasColumnType("text");

                    b.Property<string>("L_RTX_P")
                        .HasColumnType("text");

                    b.Property<string>("L_SELF_REF_A")
                        .HasColumnType("text");

                    b.Property<string>("L_SELF_REF_P")
                        .HasColumnType("text");

                    b.Property<string>("L_UNBL_A")
                        .HasColumnType("text");

                    b.Property<string>("L_UNBL_P")
                        .HasColumnType("text");

                    b.Property<string>("L_WRNGD_A")
                        .HasColumnType("text");

                    b.Property<string>("L_WRNGD_P")
                        .HasColumnType("text");

                    b.Property<string>("MECHANISM_ID")
                        .HasColumnType("text");

                    b.Property<string>("MMS_1")
                        .HasColumnType("text");

                    b.Property<string>("MMS_2")
                        .HasColumnType("text");

                    b.Property<string>("MMS_3")
                        .HasColumnType("text");

                    b.Property<string>("MMS_6_A")
                        .HasColumnType("text");

                    b.Property<string>("MMS_6_P")
                        .HasColumnType("text");

                    b.Property<string>("Miss_App")
                        .HasColumnType("text");

                    b.Property<string>("Month")
                        .HasColumnType("text");

                    b.Property<string>("NEG_A")
                        .HasColumnType("text");

                    b.Property<string>("NEG_PEDS")
                        .HasColumnType("text");

                    b.Property<string>("OPD_A")
                        .HasColumnType("text");

                    b.Property<string>("OPD_P")
                        .HasColumnType("text");

                    b.Property<string>("POS_A")
                        .HasColumnType("text");

                    b.Property<string>("POS_F_A")
                        .HasColumnType("text");

                    b.Property<string>("POS_F_P")
                        .HasColumnType("text");

                    b.Property<string>("POS_M_A")
                        .HasColumnType("text");

                    b.Property<string>("POS_M_P")
                        .HasColumnType("text");

                    b.Property<string>("POS_PEDS")
                        .HasColumnType("text");

                    b.Property<string>("POS_preg")
                        .HasColumnType("text");

                    b.Property<string>("Partner")
                        .HasColumnType("text");

                    b.Property<string>("Priority_Tier")
                        .HasColumnType("text");

                    b.Property<string>("REFILL")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.Property<string>("SCREEN_A")
                        .HasColumnType("text");

                    b.Property<string>("SCREEN_ELIG_A")
                        .HasColumnType("text");

                    b.Property<string>("SCREEN_HTS_A")
                        .HasColumnType("text");

                    b.Property<string>("SCREEN_HTS_POS_A")
                        .HasColumnType("text");

                    b.Property<string>("SDI_0_7")
                        .HasColumnType("text");

                    b.Property<string>("SDI_15")
                        .HasColumnType("text");

                    b.Property<string>("SDI_8_14")
                        .HasColumnType("text");

                    b.Property<string>("Site_Name")
                        .HasColumnType("text");

                    b.Property<string>("Site_id")
                        .HasColumnType("text");

                    b.Property<string>("TB_PREV_D")
                        .HasColumnType("text");

                    b.Property<string>("TB_PREV_N")
                        .HasColumnType("text");

                    b.Property<string>("TB_PREV_NEW")
                        .HasColumnType("text");

                    b.Property<string>("TX_CURR")
                        .HasColumnType("text");

                    b.Property<string>("TX_NEW_F_A")
                        .HasColumnType("text");

                    b.Property<string>("TX_NEW_F_P")
                        .HasColumnType("text");

                    b.Property<string>("TX_NEW_M_A")
                        .HasColumnType("text");

                    b.Property<string>("TX_NEW_M_P")
                        .HasColumnType("text");

                    b.Property<string>("TX_PREV")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("VL_D_A")
                        .HasColumnType("text");

                    b.Property<string>("VL_D_P")
                        .HasColumnType("text");

                    b.Property<string>("VL_ELIG_A")
                        .HasColumnType("text");

                    b.Property<string>("VL_ELIG_P")
                        .HasColumnType("text");

                    b.Property<string>("VL_N_A")
                        .HasColumnType("text");

                    b.Property<string>("VL_N_P")
                        .HasColumnType("text");

                    b.Property<string>("Ward")
                        .HasColumnType("text");

                    b.Property<string>("XFER_DEATH")
                        .HasColumnType("text");

                    b.Property<string>("XFER_IN")
                        .HasColumnType("text");

                    b.Property<string>("XFER_OUT")
                        .HasColumnType("text");

                    b.Property<string>("Year")
                        .HasColumnType("text");

                    b.Property<string>("prep_new_o15_f")
                        .HasColumnType("text");

                    b.Property<string>("prep_new_o15_m")
                        .HasColumnType("text");

                    b.Property<string>("prep_new_u15_f")
                        .HasColumnType("text");

                    b.Property<string>("prep_new_u15_m")
                        .HasColumnType("text");

                    b.Property<string>("tx_curr_o15_f")
                        .HasColumnType("text");

                    b.Property<string>("tx_curr_o15_m")
                        .HasColumnType("text");

                    b.Property<string>("tx_curr_u15_f")
                        .HasColumnType("text");

                    b.Property<string>("tx_curr_u15_m")
                        .HasColumnType("text");

                    b.Property<string>("tx_mmd_o15_f_35mo")
                        .HasColumnType("text");

                    b.Property<string>("tx_mmd_o15_f_o6mo")
                        .HasColumnType("text");

                    b.Property<string>("tx_mmd_o15_f_u3mo")
                        .HasColumnType("text");

                    b.Property<string>("tx_mmd_o15_m_35mo")
                        .HasColumnType("text");

                    b.Property<string>("tx_mmd_o15_m_o6mo")
                        .HasColumnType("text");

                    b.Property<string>("tx_mmd_o15_m_u3mo")
                        .HasColumnType("text");

                    b.Property<string>("tx_mmd_u15_f_35mo")
                        .HasColumnType("text");

                    b.Property<string>("tx_mmd_u15_f_o6mo")
                        .HasColumnType("text");

                    b.Property<string>("tx_mmd_u15_f_u3mo")
                        .HasColumnType("text");

                    b.Property<string>("tx_mmd_u15_m_35mo")
                        .HasColumnType("text");

                    b.Property<string>("tx_mmd_u15_m_o6mo")
                        .HasColumnType("text");

                    b.Property<string>("tx_mmd_u15_m_u3mo")
                        .HasColumnType("text");

                    b.Property<string>("vmmc_circ_o15_m")
                        .HasColumnType("text");

                    b.Property<string>("vmmc_circ_u15_m")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("stg_facility_data");
                });

            modelBuilder.Entity("GHPRS.Core.Entities.FileUploads", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte[]>("File")
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UploadType")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FileUploads");
                });

            modelBuilder.Entity("GHPRS.Core.Entities.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<int>("LinkType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Link");

                    b.HasData(
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Key = "",
                            LinkType = 3,
                            Name = "Document Manager",
                            Number = 0,
                            UpdatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "/documents"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Key = "",
                            LinkType = 3,
                            Name = "DATIM",
                            Number = 0,
                            UpdatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://www.datim.org/dhis"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Key = "",
                            LinkType = 3,
                            Name = "Panaroma Dashboard",
                            Number = 0,
                            UpdatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://pepfar-panorama.org/"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Key = "",
                            LinkType = 3,
                            Name = "OHA Dashboard",
                            Number = 0,
                            UpdatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://sites.google.com/a/usaid.gov/gh-oha/home/reports-resources/quarterly-reporting-guidance-and-resources"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Key = "",
                            LinkType = 3,
                            Name = "Partner Performance Report",
                            Number = 0,
                            UpdatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://www.pepfar.net/OGAC-HQ/icpi/Products/Forms/AllItems.aspx"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Key = "",
                            LinkType = 3,
                            Name = "Monthly Portal",
                            Number = 0,
                            UpdatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://hmis.reachproject.or.tz/MonthlyReporting/"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Key = "",
                            LinkType = 3,
                            Name = "IP Reporting System",
                            Number = 0,
                            UpdatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://usaidtanzaniaiprs.com/index.cfm"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Key = "",
                            LinkType = 3,
                            Name = "STAT Compiler",
                            Number = 0,
                            UpdatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://statcompiler.com/en/"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Key = "",
                            LinkType = 3,
                            Name = "UNICEF (MICS)",
                            Number = 0,
                            UpdatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://data.unicef.org/"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Key = "",
                            LinkType = 3,
                            Name = "Global Health Data",
                            Number = 0,
                            UpdatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://apps.who.int/gho/data/node.home"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Key = "",
                            LinkType = 3,
                            Name = "World Bank",
                            Number = 0,
                            UpdatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://data.worldbank.org/"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Key = "",
                            LinkType = 3,
                            Name = "World Bank Service Delivery Indicators",
                            Number = 0,
                            UpdatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://datatopics.worldbank.org/sdi/"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Key = "",
                            LinkType = 3,
                            Name = "WHO Global Health Observatory",
                            Number = 0,
                            UpdatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "/Observatory"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Key = "80334b54cc4c696b67e0d20c2bc461b9d867781b4234af3819030209cbde6751",
                            LinkType = 0,
                            Name = "Pediatric ARV Optimization",
                            Number = 5,
                            UpdatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://52.251.58.64:3000"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Key = "80334b54cc4c696b67e0d20c2bc461b9d867781b4234af3819030209cbde6751",
                            LinkType = 0,
                            Name = "D5 USAID Monthly Reporting",
                            Number = 12,
                            UpdatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://52.251.58.64:3000"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Key = "80334b54cc4c696b67e0d20c2bc461b9d867781b4234af3819030209cbde6751",
                            LinkType = 0,
                            Name = "D5 USAID Monthly Reporting - Site Level",
                            Number = 13,
                            UpdatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://52.251.58.64:3000"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Key = "80334b54cc4c696b67e0d20c2bc461b9d867781b4234af3819030209cbde6751",
                            LinkType = 0,
                            Name = "MCH FP Performance Dashboard",
                            Number = 14,
                            UpdatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://52.251.58.64:3000"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Key = "80334b54cc4c696b67e0d20c2bc461b9d867781b4234af3819030209cbde6751",
                            LinkType = 0,
                            Name = "Boresha Afya Facilities",
                            Number = 36,
                            UpdatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://52.251.58.64:3000"
                        });
                });

            modelBuilder.Entity("GHPRS.Core.Entities.Lookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LookupType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Lookups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LookupType = 0,
                            Name = "Male",
                            UpdatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LookupType = 0,
                            Name = "Female",
                            UpdatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LookupType = 1,
                            Name = "Single",
                            UpdatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LookupType = 1,
                            Name = "Married",
                            UpdatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LookupType = 1,
                            Name = "Divorced",
                            UpdatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LookupType = 1,
                            Name = "Widow",
                            UpdatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LookupType = 1,
                            Name = "Widower",
                            UpdatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LookupType = 2,
                            Name = "TEXT",
                            UpdatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "TEXT"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LookupType = 2,
                            Name = "DATE",
                            UpdatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "DATE"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LookupType = 2,
                            Name = "NUMBER",
                            UpdatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "NUMERIC"
                        });
                });

            modelBuilder.Entity("GHPRS.Core.Entities.MerData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("age_2018")
                        .HasColumnType("text");

                    b.Property<string>("age_2019")
                        .HasColumnType("text");

                    b.Property<string>("ageasentered")
                        .HasColumnType("text");

                    b.Property<string>("award_number")
                        .HasColumnType("text");

                    b.Property<string>("categoryoptioncomboname")
                        .HasColumnType("text");

                    b.Property<string>("community")
                        .HasColumnType("text");

                    b.Property<string>("communityuid")
                        .HasColumnType("text");

                    b.Property<string>("country")
                        .HasColumnType("text");

                    b.Property<string>("cumulative")
                        .HasColumnType("text");

                    b.Property<string>("disaggregate")
                        .HasColumnType("text");

                    b.Property<string>("dreams")
                        .HasColumnType("text");

                    b.Property<string>("facility")
                        .HasColumnType("text");

                    b.Property<string>("facilityuid")
                        .HasColumnType("text");

                    b.Property<string>("fiscal_year")
                        .HasColumnType("text");

                    b.Property<string>("funding_agency")
                        .HasColumnType("text");

                    b.Property<string>("hiv_treatment_status")
                        .HasColumnType("text");

                    b.Property<string>("indicator")
                        .HasColumnType("text");

                    b.Property<string>("indicatortype")
                        .HasColumnType("text");

                    b.Property<string>("mech_code")
                        .HasColumnType("text");

                    b.Property<string>("mech_name")
                        .HasColumnType("text");

                    b.Property<string>("modality")
                        .HasColumnType("text");

                    b.Property<string>("numeratordenom")
                        .HasColumnType("text");

                    b.Property<string>("operatingunit")
                        .HasColumnType("text");

                    b.Property<string>("operatingunituid")
                        .HasColumnType("text");

                    b.Property<string>("orgunituid")
                        .HasColumnType("text");

                    b.Property<string>("otherdisaggregate")
                        .HasColumnType("text");

                    b.Property<string>("otherdisaggregate_sub")
                        .HasColumnType("text");

                    b.Property<string>("prime_partner_duns")
                        .HasColumnType("text");

                    b.Property<string>("prime_partner_name")
                        .HasColumnType("text");

                    b.Property<string>("prime_partner_uei")
                        .HasColumnType("text");

                    b.Property<string>("psnu")
                        .HasColumnType("text");

                    b.Property<string>("psnuuid")
                        .HasColumnType("text");

                    b.Property<string>("qtr1")
                        .HasColumnType("text");

                    b.Property<string>("qtr2")
                        .HasColumnType("text");

                    b.Property<string>("qtr3")
                        .HasColumnType("text");

                    b.Property<string>("qtr4")
                        .HasColumnType("text");

                    b.Property<string>("sex")
                        .HasColumnType("text");

                    b.Property<string>("sitename")
                        .HasColumnType("text");

                    b.Property<string>("sitetype")
                        .HasColumnType("text");

                    b.Property<string>("snu1")
                        .HasColumnType("text");

                    b.Property<string>("snu1uid")
                        .HasColumnType("text");

                    b.Property<string>("snuprioritization")
                        .HasColumnType("text");

                    b.Property<string>("source_name")
                        .HasColumnType("text");

                    b.Property<string>("standardizeddisaggregate")
                        .HasColumnType("text");

                    b.Property<string>("statuscx")
                        .HasColumnType("text");

                    b.Property<string>("statushiv")
                        .HasColumnType("text");

                    b.Property<string>("statustb")
                        .HasColumnType("text");

                    b.Property<string>("targets")
                        .HasColumnType("text");

                    b.Property<string>("trendscoarse")
                        .HasColumnType("text");

                    b.Property<string>("typemilitary")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("stg_mer_data");
                });

            modelBuilder.Entity("GHPRS.Core.Entities.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Organizations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "USAID",
                            Name = "USAID",
                            ShortName = "USAID",
                            Status = 0,
                            UpdatedAt = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("GHPRS.Core.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("GenderId")
                        .HasColumnType("integer");

                    b.Property<int>("MaritalStatusId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("GHPRS.Core.Entities.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<byte[]>("File")
                        .HasColumnType("bytea");

                    b.Property<string>("FileExtension")
                        .HasColumnType("text");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Version")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("GHPRS.Core.Entities.Upload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte[]>("File")
                        .HasColumnType("bytea");

                    b.Property<string>("FileExtension")
                        .HasColumnType("text");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UploadBatch")
                        .HasColumnType("text");

                    b.Property<Guid>("UploadBatchGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("UploadStatus")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("TemplateId");

                    b.HasIndex("UserId");

                    b.ToTable("Uploads");
                });

            modelBuilder.Entity("GHPRS.Core.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("PersonId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("GHPRS.Core.Entities.WorkSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Range")
                        .HasColumnType("text");

                    b.Property<string>("TableName")
                        .HasColumnType("text");

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("WorkSheets");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GHPRS.Core.Entities.Column", b =>
                {
                    b.HasOne("GHPRS.Core.Entities.WorkSheet", "WorkSheet")
                        .WithMany("Columns")
                        .HasForeignKey("WorkSheetId");

                    b.Navigation("WorkSheet");
                });

            modelBuilder.Entity("GHPRS.Core.Entities.FileUploads", b =>
                {
                    b.HasOne("GHPRS.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GHPRS.Core.Entities.Upload", b =>
                {
                    b.HasOne("GHPRS.Core.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GHPRS.Core.Entities.Template", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId");

                    b.HasOne("GHPRS.Core.Entities.User", "User")
                        .WithMany("Uploads")
                        .HasForeignKey("UserId");

                    b.Navigation("Organization");

                    b.Navigation("Template");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GHPRS.Core.Entities.User", b =>
                {
                    b.HasOne("GHPRS.Core.Entities.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GHPRS.Core.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("GHPRS.Core.Entities.WorkSheet", b =>
                {
                    b.HasOne("GHPRS.Core.Entities.Template", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GHPRS.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GHPRS.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GHPRS.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GHPRS.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GHPRS.Core.Entities.Organization", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("GHPRS.Core.Entities.User", b =>
                {
                    b.Navigation("Uploads");
                });

            modelBuilder.Entity("GHPRS.Core.Entities.WorkSheet", b =>
                {
                    b.Navigation("Columns");
                });
#pragma warning restore 612, 618
        }
    }
}
