using GHPRS.Core.Entities;
using System.Collections.Generic;
using System.Linq;
using GHPRS.Core.Interfaces;
using Microsoft.EntityFrameworkCore;
using static GHPRS.Core.Entities.Template;
using System;
using System.Data;

namespace GHPRS.Persistence.Repositories
{
    public class TemplateRepository : Repository<Template>, ITemplateRepository
    {
        private readonly DbSet<Template> _entities;
        private readonly GhprsContext _context;
        public TemplateRepository(GhprsContext context) : base(context)
        {
            _entities = context.Set<Template>();
            _context = context;
        }

        public void CreateTemplateTable(string name, DataTable data)
        {
            string columnsValues = String.Empty;
            foreach (DataColumn column in data.Columns)
            {
                columnsValues += $"\"{column}\" TEXT, ";
            }
            FormattableString createScript = $"CREATE TABLE public.\"{name}\" ( \"Id\" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ) CONSTRAINT \"PK_{name}\" PRIMARY KEY (\"Id\"));";

            try
            {
                _context.Database.ExecuteSqlInterpolated(createScript);
            }
            catch (Exception e)
            {
                throw e;
            }
            
        }

        public IEnumerable<Template> GetAllFull()
        {
            return _entities;
        }

        public Template GetAllFullById(int id)
        {
            return _entities.SingleOrDefault(s => s.Id == id);
        }

        public object GetDetailsById(int id)
        {
            var result = _entities.Select(s => new { s.Id, s.Name, s.Description, s.ContentType, s.Version, s.Frequency, s.Status, s.CreatedAt }).FirstOrDefault(x => x.Id == id);
            return result;
        }

        public IEnumerable<object> GetList(string role)
        {
            if (role == "Administrator")
            {
                return _entities.Select(s => new { s.Id, s.Name, s.Description, s.ContentType, s.Version, s.Frequency, s.Status, s.CreatedAt }).ToList();
            }
            else
            {
                return _entities.Select(s => new { s.Id, s.Name, s.Description, s.ContentType, s.Version, s.Frequency, s.Status, s.CreatedAt }).Where(x => x.Status == TemplateStatus.Active).ToList();
            }
            
        }
    }
}
 